# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2022-05-01T05:01:14+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Video(BaseModel):
    link_1080p: str = Field(..., alias='1080p')
    link_720p: str = Field(..., alias='720p')
    link_480p: str = Field(..., alias='480p')
    link_360p: str = Field(..., alias='360p')


class Movie(BaseModel):
    movie: str
    year: int
    release_date: str
    director: str
    character: str
    movie_duration: str
    timestamp: str
    full_line: str
    current_wow_in_movie: int
    total_wows_in_movie: int
    poster: str
    video: Video
    audio: str


class MovieList(BaseModel):
    __root__: List[Movie]
